services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crowbank-app-dev
    restart: unless-stopped
    ports:
      - "2222:22"    # SSH for devuser
      - "5000:5000"  # Flask dev server
    volumes:
      - ./:/app  # Mount project source
      - ./config/yaml/secret.yaml:/app/config/yaml/secret.yaml:ro  # Mount secrets (read-only)
    networks:
      - dev-net
    # No secrets in environment variables; app reads from mounted secret.yaml

  crowbank-postgres:
    image: postgres:16-alpine
    container_name: crowbank-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-crowbank}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-crowbank}
    ports:
      - "5432:5432"  # Default Postgres port
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev-net

  postgres-mcp-server:
    image: mcp/postgres
    container_name: crowbank-postgres-mcp-local
    restart: unless-stopped
    command: ["node", "dist/index.js", "postgresql://crowbank:ZhV8Pk521j1Z@192.168.0.201:54320/crowbank"]
    ports:
      - "3001:3001"
    networks:
      - dev-net

  github-mcp-server:
    image: ghcr.io/github/github-mcp-server
    container_name: crowbank-github-mcp-local
    restart: unless-stopped
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_TOKEN}
    # ports:
    #   - "5432:5432"  # Commented out to avoid conflict with main Postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crowbank"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev-net

  pgadmin:
    image: dpage/pgadmin4:9.4
    container_name: crowbank-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@crowbank.co.uk}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-changeme}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      crowbank-postgres:
        condition: service_healthy
    networks:
      - dev-net

volumes:
  pgdata:
    name: crowbank_pgdata
  pgadmin_data:
    name: crowbank_pgadmin

networks:
  dev-net:
    name: dev-network
