version: '3.8'

services:
  crowbank-postgres:
    image: postgres:latest
    container_name: crowbank-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: crowbank-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "securepassword"
    ports:
      - "8080:80"
    depends_on:
      - crowbank-postgres

volumes:
  pgdata:
