services:
  postgres-mcp-server:
    image: mcp/postgres
    container_name: crowbank-postgres-mcp-local
    restart: unless-stopped
    command: ["node", "dist/index.js", "postgresql://crowbank:ZhV8Pk521j1Z@192.168.0.201:54320/crowbank"]
    ports:
      - "3001:3001"

  github-mcp-server:
    image: ghcr.io/github/github-mcp-server
    container_name: crowbank-github-mcp-local
    restart: unless-stopped
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_TOKEN}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crowbank"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:9.4
    container_name: crowbank-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@crowbank.co.uk}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-changeme}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      crowbank-postgres:
        condition: service_healthy

  redis:
    image: redis:alpine
    container_name: crowbank-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    name: crowbank_pgdata
  pgadmin_data:
    name: crowbank_pgadmin
  redis_data:
    name: crowbank_redis
