"""Add notes, banned, opt_out, discount to Customer

Revision ID: 86ca15789c6a
Revises: 
Create Date: 2025-04-20 17:08:32.575019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ca15789c6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('banned', sa.Boolean(), nullable=False))
    op.add_column('customers', sa.Column('opt_out', sa.Boolean(), nullable=False))
    op.add_column('customers', sa.Column('discount', sa.Numeric(precision=5, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'discount')
    op.drop_column('customers', 'opt_out')
    op.drop_column('customers', 'banned')
    op.drop_column('customers', 'notes')
    # ### end Alembic commands ###
